// apps/reactRemote/src/app/app.tsx
import React from 'react';
import styles from './app.module.scss';

export function App() {
  return (
    <div className="card border-info shadow-sm px-4 py-3">
      <div className="hstack justify-content-between align-items-start mb-3">
        <div>
          <h2 className="text-info">React App</h2>
          <p className="m-0 fw-semibold">Web Component</p>
        </div>
        <img src="/assets/images/react.png" alt="React Logo" className={`img-fluid ${styles.logo}`} />
      </div>
      <p className="text-secondary fst-italic">Version: {React.version}</p>
    </div>
  );
}

export default App;

// apps/vueRemote/src/app/App.vue
<script setup lang="ts">
import '../styles.scss';
import { version } from 'vue';

const vueVersion = version;
</script>

<template>
  <div class="card border-success shadow-sm px-4 py-3">
    <div class="hstack justify-content-between align-items-start mb-3">
      <div>
        <h2 class="text-success">
          Vue App
        </h2>
        <p class="m-0 fw-semibold">
          Web Component
        </p>
      </div>
      <img 
        class="img-fluid logo" 
        :src="'/assets/images/vue.png'"
        alt="Vue Logo"
      >
    </div>
    <p class="text-secondary fst-italic">
      Version: {{ vueVersion }}
    </p>
  </div>
</template>

<style scoped>
  .logo {
    height: 75px;
    max-height: 75px;
  }
</style>
